# Generated by Django 3.2.4 on 2021-07-15 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_machinestate_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
