# Generated by Django 3.2.4 on 2021-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_machinestate_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsToGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
    ]
