# Generated by Django 3.2.4 on 2021-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_tagsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagstoget',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
