# Generated by Django 3.2.4 on 2021-08-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_tagstoget_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagstoget',
            name='display_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='tagstoget',
            name='unit',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
