# Generated by Django 3.2.4 on 2021-08-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210806_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagstoget',
            name='display_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tagstoget',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
