# Generated by Django 3.2.4 on 2021-08-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20210806_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=50)),
                ('limit_upper', models.FloatField(default=999)),
                ('limit_lower', models.FloatField(default=0)),
            ],
        ),
    ]
